### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by noaham** [BenjaminVanRyseghem/next-action-clojure#2]
I get the following error when trying to run the server on OS X with leningen:

```
Exception in thread "main" java.lang.NullPointerException
    at clojure.core$swap_BANG_.invoke(core.clj:2161)
    at next_action.todoist$attach_tasks.invoke(todoist.clj:30)
    at next_action.todoist$get_projects.invoke(todoist.clj:140)
    at next_action.sync$update.invoke(sync.clj:8)
    at next_action.core$update.invoke(core.clj:17)
    at next_action.core$_main.doInvoke(core.clj:25)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.Var.invoke(Var.java:411)
    at user$eval5.invoke(form-init920060420985399842.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6609)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.Compiler.loadFile(Compiler.java:7020)
    at clojure.main$load_script.invoke(main.clj:294)
    at clojure.main$init_opt.invoke(main.clj:299)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

I know it's probably something I am doing wrong rather than a bug, however I wasn't able to sort it out myself so I'd appreciate it if you could point me in the right direction.

**Comment by BenjaminVanRyseghem** [comment]
It works for me.
- Do you have a `info.json` file?
- Does it match the pattern defined [here](https://github.com/BenjaminVanRyseghem/next-action-clojure#infojson-structure)?

**Comment by noaham** [comment]
Yep, it is: 

```
{
    "api-token": "XXXXXXXXXXXXXX",
    "someday-label": "someday",
    "list-prefix": "--",
    "next-action-label": "next_action",
    "parallel-postfix": "=",
    "sleeping-time": 1
}
```

**Comment by noaham** [comment]
I must have changed something as the error is now:

```
Exception in thread "main" java.lang.StackOverflowError
    at clojure.lang.PersistentHashMap$BitmapIndexedNode.assoc(PersistentHashMap.java:586)
    at clojure.lang.PersistentHashMap.assoc(PersistentHashMap.java:142)
    at clojure.lang.PersistentHashSet.cons(PersistentHashSet.java:99)
    at clojure.lang.PersistentHashSet.createWithCheck(PersistentHashSet.java:54)
    at clojure.lang.RT.set(RT.java:1474)
    at next_action.nextaction$contains_next_action_label_QMARK_.invoke(nextaction.clj:39)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_.invoke(nextaction.clj:51)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309$fn__4310.invoke(nextaction.clj:55)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309.invoke(nextaction.clj:54)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$dorun.invoke(core.clj:2780)
```

**Comment by BenjaminVanRyseghem** [comment]
Mine looks like:

``` json
{
    "api-token": "SECRET",
    "someday-label": "Someday",
    "list-prefix": "List -",
    "next-action-label": "next-action",
    "parallel-postfix": "=",
    "sleeping-time": 10
}
```

What is the output of

```
$ lein --version
```

Mine is:

```
Leiningen 2.5.0 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by noaham** [comment]
Ok so I have updated java so that it is exactly the same version as yours (leinengen is also 2.5.0). I have made my info.json exactly the same as yours (except for the API key!) and now the error has changed slightly:

```
Exception in thread "main" java.lang.StackOverflowError
    at next_action.todoist$get_next_action_id.invoke(todoist.clj:126)
    at next_action.nextaction$contains_next_action_label_QMARK_.invoke(nextaction.clj:39)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_.invoke(nextaction.clj:51)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309$fn__4310.invoke(nextaction.clj:55)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309.invoke(nextaction.clj:54)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$dorun.invoke(core.clj:2780)
    at clojure.core$doall.invoke(core.clj:2796)
```

**Comment by BenjaminVanRyseghem** [comment]
then I have no clue at all :panda_face:

**Comment by noaham** [comment]
Thanks for having a look. I'll try testing on a different machine and see what comes of that. Close the issue, if I can reproduce it consistently I will let you know.

**Comment by BenjaminVanRyseghem** [comment]
I do have the same issue now :smile: 
(I thought the stack trace was because I was quitting the app)
I will have a look

**Comment by BenjaminVanRyseghem** [comment]
I assume something change in Todoist API since even the deployed jar that I have is now failing

**Comment by BenjaminVanRyseghem** [comment]
Just pushed a fix

Hopefully it will work better now :smile: 
Thanks for the feedback

**Comment by noaham** [comment]
Cheers! Its still not working for me, but if it's working for you then it is certainly a problem on my end!

**Comment by BenjaminVanRyseghem** [comment]
What's your issue? Still the same?

**Comment by noaham** [comment]
The error that I get is almost the same:

```
Exception in thread "main" java.lang.StackOverflowError
    at next_action.nextaction$contains_next_action_label_QMARK_.invoke(nextaction.clj:39)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_.invoke(nextaction.clj:51)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309$fn__4310.invoke(nextaction.clj:55)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309.invoke(nextaction.clj:54)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$dorun.invoke(core.clj:2780)
    at clojure.core$doall.invoke(core.clj:2796)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_.invoke(nextaction.clj:54)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309$fn__4310.invoke(nextaction.clj:55)
    at next_action.nextaction$remove_patches_for_sequential_task_BANG_$iter__4304__4308$fn__4309.invoke(nextaction.clj:54)
...
```

**Comment by BenjaminVanRyseghem** [comment]
Maybe it's a problem in the way your todoist tickets are organized. Could you tell me more about it?

**Comment by noaham** [comment]
I'm not sure what you mean. I have quite a few projects with subprojects (and subsubprojects). I also use labels to give a context to each task, but thats about it. I will see if it works with a simpler setup

**Comment by BenjaminVanRyseghem** [comment]
I'll have a deeper look tomorrow (but today is the release of Super Smash Bros, so I am quite busy :smile:)

**Comment by noaham** [comment]
Ha! Great! I will have a play around with it, but as I said if yours is working then its a problem on my end so don't worry about it!

**Comment by noaham** [comment]
Ok I have it working on a very simple setup! Just 5 tasks in one project. Let me play with it over the weekend and Ill be able to tell you exactly what makes it break.

**Comment by noaham** [comment]
Ok so it seems that the minimal non working example is two tasks with each with a subtask in the same project (if they are in different projects then it does not break). E.g if there is a single project with the tasks

```
+ Task 1
    + Subtask 1.1
+ Task 2
    +Subtask 2.1
```

I have set it up in a new todoist account and emailed you the login details and api key so that you can test it.

What I haven't been able to work out is if this is a problem with the tidiest api of with something going wrong in the clojure code.

There is a workaround to get this working. If the tasks are added one at a time and the next-actions program is allowed to add them one at a time then is wont fail, as long as two tasks with subtasks in the same project aren't being added at the same time.

**Comment by BenjaminVanRyseghem** [comment]
There is an error in the way sub tasks are managed (since I never used some, I never had this error).
I have a patch ready, I am just testing a bit more now

**Comment by noaham** [comment]
Working great for me now!
